micronaut:
  application:
    name: pixGrpc
datasources:
  default:
    url: jdbc:postgresql://localhost:5432/cdc
    driverClassName: org.postgresql.Driver
    username: postgres
    password: Zup@2206
    dialect: POSTGRES

jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true
        format_sql: true
